# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
flutter_login_application_path = '../yody_login'
load File.join(flutter_login_application_path, '.ios', 'Flutter', 'podhelper.rb')
require_relative '../yody_food/node_modules/react-native/scripts/react_native_pods'
require_relative '../yody_food/node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../yody_employee/node_modules/react-native/scripts/react_native_pods'
require_relative '../yody_employee/node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'yody_micro_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_login_application_path)
    # Flags change depending on the env values.
  flags = get_default_flags()
  use_react_native!(:path => '../yody_food/node_modules/react-native')

  # Pods for yody_micro_swift
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    flutter_post_install(installer) if defined?(flutter_post_install)
  end
end
